import Head from "next/head";
import Banner from "../components/Banner";
import Header from "../components/Header";

export default function Home({ exploreData }) {
  console.log(exploreData);
  return (
    <div>
      <Head>
        <title>Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Banner />

      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        <section className="pt-6">
          <h2 className="text-4xl font-semibold pb-5">Explore Nearby</h2>
          {/* {exploreData !== undefined && exploreData.content.detailed.map((item) => (
            <h1>{item.city}</h1>
          ))} */}
        </section>
      </main>
    </div>
  );
}

// This is running inside a server
export async function getStaticProps() {
  const exploreData = await fetch("../cities.json").then(
    (res) => res.json()
  );
 
  return {
    props: {
      exploreData
    }
  }
}

