import Head from "next/head";
import Banner from "../components/Banner";
import Header from "../components/Header";
import fsPromises from "fs/promises";
import path from "path";
import Cities from "../cities.json";
import SmallCard from "../components/SmallCard";

// This is running inside a server
export async function getStaticProps() {
  const filePath = path.join(process.cwd(), "cities.json");
  const jsonData = await fsPromises.readFile(filePath);
  const exploreData = JSON.parse(jsonData);

  return {
    props: {
      exploreData,
    },
  };
}

export default function Home({ exploreData }) {
  console.log(exploreData);
  return (
    <div>
      <Head>
        <title>Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Banner />

      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        <section className="pt-6">
          <h2 className="text-4xl font-semibold pb-5">Explore Nearby</h2>
          {exploreData.nearbyCities?.map((item, index) => (
            <SmallCard
              key={index}
              img={item.img}
              location={item.location}
              distance={item.distance}
            />
          ))}
        </section>
      </main>
    </div>
  );
}
